# Generated by Django 4.2.5 on 2023-09-17 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soko', '0004_remove_soko_ghala_soko_ghala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myghala', '0002_rename_bags_sold_myghala_bags_stored_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySoko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_sold', models.IntegerField(default=0)),
                ('bags_sold', models.IntegerField(default=0)),
                ('date_sold', models.DateTimeField(default=django.utils.timezone.now)),
                ('my_ghala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myghala.myghala')),
                ('soko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soko.soko')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
