# Generated by Django 4.2.5 on 2023-09-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ghala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghala_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('capacity', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='images/')),
                ('start_price', models.IntegerField(default=0)),
                ('rent_price', models.IntegerField(default=0)),
            ],
        ),
    ]
