# Generated by Django 4.2.5 on 2023-09-16 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ghalas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ghalas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[ghalas.models.validate_rating, ghalas.models.validate_unique_rating])),
                ('ghala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ghalas.ghala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
