# Generated by Django 4.2.5 on 2023-09-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghalas', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ghala',
            new_name='ghala_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='user_id',
        ),
    ]
