# Generated by Django 4.2.5 on 2023-09-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghalas', '0003_rename_ghala_rating_ghala_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ghala_id',
            new_name='ghala',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
