# Generated by Django 4.2.5 on 2023-09-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghalas', '0004_rename_ghala_id_rating_ghala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ghala',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ghalas.ghala'),
        ),
    ]
