# Generated by Django 4.2.5 on 2023-09-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghalas', '0005_alter_rating_ghala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ghala',
        ),
        migrations.AddField(
            model_name='rating',
            name='ghala',
            field=models.ManyToManyField(related_name='ratings', to='ghalas.ghala'),
        ),
    ]
