# Generated by Django 4.2.5 on 2023-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blogdefault.jpg', upload_to='blog/images/'),
        ),
    ]
