# Generated by Django 4.2.5 on 2024-03-04 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_blog_created_at_blog_updated_at_alter_blog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("62470f15-bfd9-4e3a-863d-71673e180818"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
