# Generated by Django 4.2.5 on 2024-03-04 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_blog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8439c6c3-d610-4ee4-9278-ac7757e9b0fa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
