# Generated by Django 4.2.5 on 2024-03-04 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_blog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("26ef22eb-4653-49d3-83b5-e0ff1f6f7f73"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
