# Generated by Django 4.2.5 on 2024-03-04 18:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blogcategories", "0001_initial"),
        ("blog", "0009_alter_blog_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogcategories.blogcategory",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("61281d27-f1b3-434f-8212-6f13622d1e2a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
