# Generated by Django 4.2.5 on 2023-09-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghalas', '0006_remove_rating_ghala_rating_ghala'),
        ('soko', '0002_remove_soko_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soko',
            name='ghala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghalas.ghala'),
        ),
    ]
