# Generated by Django 4.2.5 on 2023-09-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghalas', '0006_remove_rating_ghala_rating_ghala'),
        ('soko', '0003_alter_soko_ghala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soko',
            name='ghala',
        ),
        migrations.AddField(
            model_name='soko',
            name='ghala',
            field=models.ManyToManyField(to='ghalas.ghala'),
        ),
    ]
