# Generated by Django 4.2.5 on 2023-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_farmer',
            field=models.BooleanField(default=True),
        ),
    ]
