# Generated by Django 4.2.5 on 2024-03-04 16:18

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_newuser_is_farmer"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="newuser",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9c1d875d-ff74-4a0d-b5f3-796167a7665b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
