# Generated by Django 4.2.5 on 2024-03-04 16:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="farmerprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("62470f15-bfd9-4e3a-863d-71673e180818"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
