# Generated by Django 4.2.5 on 2024-03-04 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Profile", "0003_alter_farmerprofile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="address",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="phone_number",
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="farmerprofile",
            name="avatar",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="farmerprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("36833432-09c7-4105-acde-72647a442c8f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
