# Generated by Django 4.2.5 on 2024-03-04 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Profile", "0005_alter_farmerprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("61281d27-f1b3-434f-8212-6f13622d1e2a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
