# Generated by Django 4.2.5 on 2024-03-04 16:59

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8439c6c3-d610-4ee4-9278-ac7757e9b0fa"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
