# Generated by Django 4.2.5 on 2024-03-04 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("36833432-09c7-4105-acde-72647a442c8f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
