# Generated by Django 4.2.5 on 2023-09-16 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ghalas', '0004_rename_ghala_id_rating_ghala_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGhala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags_sold', models.IntegerField(default=0)),
                ('date_rented', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_of_storage', models.IntegerField(default=0)),
                ('ghala', models.ManyToManyField(to='ghalas.ghala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
