# Generated by Django 4.2.5 on 2023-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soko', '0004_remove_soko_ghala_soko_ghala'),
        ('myghala', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myghala',
            old_name='bags_sold',
            new_name='bags_stored',
        ),
        migrations.AddField(
            model_name='myghala',
            name='commodity_stored',
            field=models.ManyToManyField(related_name='ghalas_stored', to='soko.soko'),
        ),
    ]
